module CalculatorApp{
    interface ICalculatorModel{
    double getSum(in double a, in double b);
    double getSub(in double a, in double b);
    double getMul(in double a, in double b);
    double getDiv(in double a, in double b);
    };
};